import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
test('membership isolation, owner invitations and stale-save protection',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;
 create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated;
 create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
 create table storage.objects(id uuid,name text,bucket_id text);alter table storage.objects enable row level security;
 grant usage on schema storage to authenticated;grant select,insert,delete on storage.objects to authenticated;
 create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;
 insert into auth.users values('00000000-0000-0000-0000-000000000001','owner@example.test',now()),('00000000-0000-0000-0000-000000000002','member@example.test',now()),('00000000-0000-0000-0000-000000000003','outsider@example.test',now());`);
 await db.exec(await readFile('supabase/migrations/202609130001_workspaces.sql','utf8'));
 const as=async n=>{await db.exec("set role authenticated;set request.jwt.claim.sub='00000000-0000-0000-0000-00000000000"+n+"'")};
 await as(1);
 const w=(await db.query("select public.ef_create_workspace('Audit team') as id")).rows[0].id;
 const document={evidence:[],actions:[],tests:[]};
 await db.query("insert into storage.objects(id,name,bucket_id) values(gen_random_uuid(),$1,'evidenceflow')",[w+'/evidence/file']);
 assert.equal((await db.query('select public.ef_save_workspace($1,0,$2) as revision',[w,document])).rows[0].revision,1);
 await assert.rejects(db.query('select public.ef_save_workspace($1,0,$2)',[w,document]),/CONFLICT/);
 await as(3);assert.equal((await db.query('select * from public.ef_workspaces')).rows.length,0);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await assert.rejects(db.query("insert into storage.objects(id,name,bucket_id) values(gen_random_uuid(),$1,'evidenceflow')",[w+'/intruder/file']),/row-level security/);
 await assert.rejects(db.query('select public.ef_save_workspace($1,1,$2)',[w,document]),/denied/);
 await assert.rejects(db.query('select public.ef_invite_member($1,$2)',[w,'member@example.test']),/Only/);
 await as(1);await db.query('select public.ef_invite_member($1,$2)',[w,'member@example.test']);
 await as(2);await db.query('select public.ef_accept_invites()');
 assert.equal((await db.query('select * from public.ef_workspaces')).rows.length,1);
 assert.equal((await db.query('select * from storage.objects')).rows.length,1);
 await db.query('select public.ef_save_workspace($1,1,$2)',[w,document]);
 await assert.rejects(db.query('update public.ef_workspaces set revision=99'),/permission denied/);
 await as(1);await db.query("select public.ef_remove_member($1,'00000000-0000-0000-0000-000000000002')",[w]);
 await as(2);assert.equal((await db.query('select * from public.ef_workspaces')).rows.length,0);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await db.close();
});
