import { createClient } from '@supabase/supabase-js';

const config=window.EVIDENCEFLOW_CONFIG||{};
const configured=Boolean(config.supabaseUrl&&config.supabaseKey);
const client=configured?createClient(config.supabaseUrl,config.supabaseKey):null;
let session=null,workspace=null,revision=0,busy=false;
const status=document.createElement('div');
status.className='team-tools';
status.innerHTML='<button class="btn" id="team-account">Team account</button><select id="team-workspace" aria-label="Shared workspace" hidden></select><button class="btn secondary" id="team-refresh" hidden>Refresh shared data</button><span id="team-state" role="status">Personal workspace</span>';
document.querySelector('.workspace-tools').append(status);
const dialog=document.createElement('dialog');dialog.className='dialog team-dialog';dialog.setAttribute('aria-label','Team account');document.body.append(dialog);
const message=()=>dialog.querySelector('[role=status]');
function errorText(error){return error?.message||String(error)}
function setState(text){status.querySelector('#team-state').textContent=text}
function check(result){if(result.error)throw result.error;return result.data}
function lock(value){document.getElementById('form').querySelectorAll('button').forEach(b=>b.disabled=value)}
function restorePersonal(){workspace=null;window.EvidenceFlowCloud.active=false;data=JSON.parse(localStorage.getItem('evidenceflow-data')||'null')||structuredClone(seed);data.tests||=[];document.querySelector('.local-notice').textContent='Personal workspace · Records and files are stored in this browser.';document.querySelector('.workspace').firstChild.textContent='Personal workspace ';document.getElementById('team-refresh').hidden=true;render();setState('Personal workspace')}
async function loadWorkspace(id){if(busy||document.getElementById('modal').classList.contains('open'))throw Error('Finish or cancel the open record before switching or refreshing.');const row=check(await client.from('ef_workspaces').select('*').eq('id',id).single());workspace=row;revision=row.revision;data=structuredClone(row.document);data.tests||=[];window.EvidenceFlowCloud.active=true;for(const collection of [data.evidence,data.actions,data.tests])for(const record of collection)if(record.period&&![...periodSelect.options].some(o=>o.value===record.period))periodSelect.add(new Option(record.period,record.period));document.querySelector('.local-notice').textContent='Shared workspace · Changes are saved to the team database. Use Refresh shared data to load teammates’ latest changes.';document.querySelector('.workspace').firstChild.textContent=row.name+' ';document.getElementById('team-refresh').hidden=false;render();setState('Shared · revision '+revision)}
window.EvidenceFlowCloud={active:false,async save(document){if(!workspace||!session)throw Error('Sign in and choose a workspace.');if(busy)throw Error('A save is already in progress.');busy=true;lock(true);setState('Saving…');try{revision=check(await client.rpc('ef_save_workspace',{w:workspace.id,expected_revision:revision,new_document:document}));setState('Saved to team · revision '+revision);return true}catch(error){setState('Not saved · '+errorText(error));throw error}finally{busy=false;lock(false)}}};
const localAttachment=attachment;
attachment=async function(id,file){if(!window.EvidenceFlowCloud.active)return localAttachment(id,file);if(file){const path=workspace.id+'/'+id+'/'+crypto.randomUUID();check(await client.storage.from('evidenceflow').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'}));return path}const record=data.evidence.find(x=>String(x.id)===String(id));if(!record?.remotePath)throw Error('Attach this file to the shared record first.');const blob=check(await client.storage.from('evidenceflow').download(record.remotePath));return new File([blob],record.fileName||'evidence',{type:blob.type})};
function accountMarkup(){if(!configured)return '<h2>Team setup pending</h2><p>The database connection has not been configured yet.</p><button type="button" data-close class="btn secondary">Close</button>';if(!session)return '<h2>Team account</h2><form id="auth-form"><div class="field"><label for="account-email">Email</label><input class="input" id="account-email" name="email" type="email" autocomplete="email" required></div><div class="field"><label for="account-password">Password</label><input class="input" id="account-password" name="password" type="password" minlength="8" autocomplete="current-password" required></div><div class="toolbar"><button class="btn" name="operation" value="signin">Sign in</button><button class="btn secondary" name="operation" value="signup">Create account</button></div></form><p role="status"></p><button type="button" data-close class="text-btn">Close</button>';return '<h2>Team workspace</h2><p>'+esc(session.user.email)+'</p><form id="create-workspace"><div class="field"><label for="workspace-name">New workspace name</label><input class="input" id="workspace-name" required maxlength="120"></div><button class="btn">Create workspace</button></form>'+(workspace?.owner_id===session.user.id?'<form id="invite-member"><div class="field"><label for="invite-email">Teammate email</label><input class="input" id="invite-email" type="email" required></div><button class="btn secondary">Grant workspace invitation</button><p>Ask the teammate to create an account with this email, confirm it, and sign in here. This action does not send an email.</p></form>':'')+'<p role="status"></p><div class="toolbar"><button type="button" class="btn secondary" id="signout">Sign out</button><button type="button" class="btn secondary" data-close>Close</button></div>'}
function showAccount(){dialog.innerHTML=accountMarkup();if(!dialog.open)dialog.showModal();dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelector('#auth-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const credentials={email:form.elements.email.value.trim(),password:form.elements.password.value};form.querySelectorAll('button').forEach(b=>b.disabled=true);try{if(event.submitter.value==='signup'){const result=check(await client.auth.signUp({...credentials,options:{emailRedirectTo:location.origin+location.pathname}}));message().textContent=result.session?'Account created.':'Check your email to confirm your account, then sign in.';if(result.session)await initializeSession(result.session)}else{const result=check(await client.auth.signInWithPassword(credentials));await initializeSession(result.session);showAccount()}}catch(error){message().textContent=errorText(error)}finally{form.querySelectorAll('button').forEach(b=>b.disabled=false)}});dialog.querySelector('#create-workspace')?.addEventListener('submit',async event=>{event.preventDefault();try{const id=check(await client.rpc('ef_create_workspace',{workspace_name:dialog.querySelector('#workspace-name').value.trim()}));await listWorkspaces(id);showAccount()}catch(error){message().textContent=errorText(error)}});dialog.querySelector('#invite-member')?.addEventListener('submit',async event=>{event.preventDefault();try{check(await client.rpc('ef_invite_member',{w:workspace.id,member_email:dialog.querySelector('#invite-email').value.trim()}));message().textContent='Invitation granted. The teammate can join after confirming this email and signing in.'}catch(error){message().textContent=errorText(error)}});dialog.querySelector('#signout')?.addEventListener('click',async()=>{try{check(await client.auth.signOut());session=null;restorePersonal();document.getElementById('team-workspace').hidden=true;showAccount()}catch(error){message().textContent=errorText(error)}})}
async function listWorkspaces(prefer){const rows=check(await client.from('ef_workspaces').select('id,name').order('name'));const select=document.getElementById('team-workspace');select.replaceChildren(new Option('Personal workspace',''));for(const row of rows)select.add(new Option(row.name,row.id));select.hidden=false;if(rows.length){select.value=prefer||rows[0].id;await loadWorkspace(select.value)}else{restorePersonal();setState('Signed in · create a workspace')}} 
async function initializeSession(value){session=value;if(!session){restorePersonal();return}check(await client.rpc('ef_accept_invites'));await listWorkspaces()}
document.getElementById('team-account').onclick=showAccount;
document.getElementById('team-workspace').onchange=async event=>{try{if(event.target.value)await loadWorkspace(event.target.value);else restorePersonal()}catch(error){setState(errorText(error));event.target.value=workspace?.id||''}};
document.getElementById('team-refresh').onclick=async()=>{try{await loadWorkspace(workspace.id)}catch(error){setState(errorText(error))}};
if(client){client.auth.getSession().then(({data:result,error})=>{if(error)throw error;if(result.session)return initializeSession(result.session)}).catch(error=>setState('Account connection: '+errorText(error)));client.auth.onAuthStateChange((event,value)=>{if(event==='TOKEN_REFRESHED')session=value;if(event==='SIGNED_OUT'){session=null;restorePersonal();document.getElementById('team-workspace').hidden=true}})}
